"""
Open Graph + Twitter card meta-tag contract test.

Why: OG + Twitter tags drive how the site previews in iMessage, Slack, Facebook,
LinkedIn, and every text-message client — a silent regression turns high-intent
shares into blank-preview link rot. STANDARDS §6 explicitly names "meta/OG tags
real (paste URL into a chat app — does the preview look pro?)" as a deploy gate.

Locks the tick-4 branded-card fix: asserts `og:image` and `twitter:image` point
at the 1200x630 `images/og-card.png` and NOT the 206px `images/jobsite-01.jpg`
placeholder (Slack/iMessage/Facebook crop the placeholder into a smear).
Same guard doctrine as `test_jsonld.py`'s image/logo lock.

Runs against every top-level HTML file: `index.html`, `404.html`,
`accessibility.html`, `home-repair.html`, `commercial-industrial.html`. Adding
a new top-level page? Append it to `TARGETS`.

Python 3.11+ stdlib only (`re`, `pathlib`). No pip install, no network.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX = REPO_ROOT / "index.html"
NOT_FOUND = REPO_ROOT / "404.html"
ACCESSIBILITY = REPO_ROOT / "accessibility.html"
HOME_REPAIR = REPO_ROOT / "home-repair.html"
COMMERCIAL_INDUSTRIAL = REPO_ROOT / "commercial-industrial.html"
TARGETS = (INDEX, NOT_FOUND, ACCESSIBILITY, HOME_REPAIR, COMMERCIAL_INDUSTRIAL)

# Match each <meta ...> tag broadly, then pull attributes in a second pass.
# Attribute regexes use a matched-quote backreference so an apostrophe inside a
# double-quoted content string (e.g. "This isn't live.") doesn't break parsing.
META_TAG_RE = re.compile(r'<meta\b[^>]*/?>', re.IGNORECASE)
ATTR_KEY_RE = re.compile(
    r'\b(?:property|name)\s*=\s*(?P<q>["\'])(?P<val>[^"\']+)(?P=q)',
    re.IGNORECASE,
)
ATTR_CONTENT_RE = re.compile(
    r'\bcontent\s*=\s*(?P<q>["\'])(?P<val>.*?)(?P=q)',
    re.IGNORECASE | re.DOTALL,
)

REQUIRED_OG = {"og:type", "og:title", "og:description", "og:url", "og:image"}
REQUIRED_TWITTER = {"twitter:card", "twitter:title", "twitter:description", "twitter:image"}

BRAND_CARD = "og-card.png"
PLACEHOLDER = "jobsite-01.jpg"
EXPECTED_OG_IMAGE_WIDTH = "1200"
EXPECTED_OG_IMAGE_HEIGHT = "630"
EXPECTED_OG_IMAGE_TYPE = "image/png"
EXPECTED_TWITTER_CARD = "summary_large_image"


def extract_meta(html: str) -> dict[str, str]:
    tags: dict[str, str] = {}
    for tag in META_TAG_RE.findall(html):
        key_m = ATTR_KEY_RE.search(tag)
        content_m = ATTR_CONTENT_RE.search(tag)
        if key_m is None or content_m is None:
            continue
        tags[key_m.group("val").lower()] = content_m.group("val")
    return tags


def assert_og_twitter(tags: dict[str, str], label: str) -> list[str]:
    errors: list[str] = []

    missing_og = REQUIRED_OG - tags.keys()
    if missing_og:
        errors.append(f"{label}: missing OG tags: {sorted(missing_og)}")
    missing_tw = REQUIRED_TWITTER - tags.keys()
    if missing_tw:
        errors.append(f"{label}: missing Twitter tags: {sorted(missing_tw)}")

    og_url = tags.get("og:url", "")
    if og_url and not og_url.startswith("https://"):
        errors.append(f"{label}: og:url must be absolute https, got {og_url!r}")

    og_image = tags.get("og:image", "")
    if og_image:
        if not og_image.startswith("https://"):
            errors.append(f"{label}: og:image must be absolute https, got {og_image!r}")
        if PLACEHOLDER in og_image:
            errors.append(
                f"{label}: og:image points at 206px placeholder {PLACEHOLDER!r} — "
                f"tick 4 (2026-07-06) moved this off to the branded 1200x630 og-card.png. "
                f"Preview crops turn the placeholder into a smear on Slack/iMessage/Facebook."
            )
        elif BRAND_CARD not in og_image:
            errors.append(
                f"{label}: og:image should reference {BRAND_CARD!r} (the branded 1200x630 "
                f"card generated by scripts/gen-og-card.py), got {og_image!r}"
            )

    tw_card = tags.get("twitter:card", "")
    if tw_card and tw_card != EXPECTED_TWITTER_CARD:
        errors.append(
            f"{label}: twitter:card must be {EXPECTED_TWITTER_CARD!r} to preview the "
            f"1200x630 card without cropping, got {tw_card!r}"
        )

    tw_image = tags.get("twitter:image", "")
    if tw_image:
        if not tw_image.startswith("https://"):
            errors.append(f"{label}: twitter:image must be absolute https, got {tw_image!r}")
        if PLACEHOLDER in tw_image:
            errors.append(
                f"{label}: twitter:image points at 206px placeholder {PLACEHOLDER!r} — "
                f"same rationale as og:image."
            )

    # Only assert width/height/type when og:image is present. If og:image itself is
    # missing, the "missing OG tags" error above is the real signal; dumping three
    # more "og:image:width missing" errors underneath would just be noise.
    if og_image:
        w = tags.get("og:image:width")
        if w != EXPECTED_OG_IMAGE_WIDTH:
            errors.append(f"{label}: og:image:width must be {EXPECTED_OG_IMAGE_WIDTH!r}, got {w!r}")
        h = tags.get("og:image:height")
        if h != EXPECTED_OG_IMAGE_HEIGHT:
            errors.append(f"{label}: og:image:height must be {EXPECTED_OG_IMAGE_HEIGHT!r}, got {h!r}")
        t = tags.get("og:image:type")
        if t != EXPECTED_OG_IMAGE_TYPE:
            errors.append(f"{label}: og:image:type must be {EXPECTED_OG_IMAGE_TYPE!r}, got {t!r}")

    return errors


def _valid_tags() -> dict[str, str]:
    """Minimal-but-valid tag set used as the selftest baseline."""
    return {
        "og:type": "website",
        "og:title": "Big 7 Construction — Commercial · Industrial · Residential",
        "og:description": "Two divisions, every trade in-house.",
        "og:url": "https://big7construction.com/",
        "og:image": "https://big7construction.com/images/og-card.png",
        "og:image:width": EXPECTED_OG_IMAGE_WIDTH,
        "og:image:height": EXPECTED_OG_IMAGE_HEIGHT,
        "og:image:type": EXPECTED_OG_IMAGE_TYPE,
        "twitter:card": EXPECTED_TWITTER_CARD,
        "twitter:title": "Big 7 Construction",
        "twitter:description": "Two divisions, every trade in-house.",
        "twitter:image": "https://big7construction.com/images/og-card.png",
    }


def selftest() -> int:
    baseline = _valid_tags()
    if assert_og_twitter(baseline, "selftest-baseline"):
        print("SELFTEST FAIL: baseline should be valid", file=sys.stderr)
        return 1

    cases: list[tuple[str, dict[str, str]]] = []
    b = _valid_tags(); b.pop("og:title"); cases.append(("og:title missing", b))
    b = _valid_tags(); b.pop("og:image"); cases.append(("og:image missing", b))
    b = _valid_tags(); b.pop("twitter:card"); cases.append(("twitter:card missing", b))
    b = _valid_tags(); b.pop("twitter:image"); cases.append(("twitter:image missing", b))
    b = _valid_tags(); b["og:url"] = "http://big7construction.com/"; cases.append(("og:url not https", b))
    b = _valid_tags(); b["og:image"] = "https://big7construction.com/images/jobsite-01.jpg"; cases.append(("og:image is 206px placeholder", b))
    b = _valid_tags(); b["og:image"] = "https://big7construction.com/images/random.png"; cases.append(("og:image not branded card", b))
    b = _valid_tags(); b["twitter:card"] = "summary"; cases.append(("twitter:card summary not large_image", b))
    b = _valid_tags(); b["og:image:width"] = "600"; cases.append(("og:image:width wrong", b))
    b = _valid_tags(); b["og:image:height"] = "315"; cases.append(("og:image:height wrong", b))
    b = _valid_tags(); b["og:image:type"] = "image/jpeg"; cases.append(("og:image:type wrong", b))
    b = _valid_tags(); b["twitter:image"] = "https://big7construction.com/images/jobsite-01.jpg"; cases.append(("twitter:image is 206px placeholder", b))

    failures = [name for name, tags in cases if not assert_og_twitter(tags, "selftest")]
    if failures:
        for name in failures:
            print(f"SELFTEST FAIL: mutation not caught: {name}", file=sys.stderr)
        return 1

    print(f"SELFTEST OK: baseline PASS + {len(cases)}/{len(cases)} mutations caught")
    return 0


def main() -> int:
    if "--selftest" in sys.argv:
        return selftest()

    errors: list[str] = []
    for path in TARGETS:
        if not path.exists():
            errors.append(f"{path.name} not found at {path}")
            continue
        html = path.read_text(encoding="utf-8")
        tags = extract_meta(html)
        errors.extend(assert_og_twitter(tags, path.name))

    if errors:
        for e in errors:
            print(f"FAIL: {e}", file=sys.stderr)
        return 1

    names = ", ".join(p.name for p in TARGETS)
    print(
        f"OK: {names} carry valid OG + Twitter tags; "
        f"og:image + twitter:image point at branded {BRAND_CARD} (1200x630 image/png)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
